/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://algokami.tech',
  generateRobotsTxt: true,
  sitemapSize: 7000,
  changefreq: 'monthly',
  priority: 0.7,
  exclude: ['/manifest.webmanifest'],
  robotsTxtOptions: {
    policies: [
      { userAgent: '*', allow: '/' },
      { userAgent: '*', disallow: ['/api/'] },
    ],
  },
  additionalPaths: async () => [
    { loc: '/',                    priority: 1.0 },
    { loc: '/about',               priority: 0.8 },
    { loc: '/blog',                priority: 0.7 },
    { loc: '/contact',             priority: 0.8 },
    { loc: '/enquiries',           priority: 0.7 },
    { loc: '/get-quote',           priority: 0.8 },
    { loc: '/privacy-policy',      priority: 0.6 },
    { loc: '/refund-policy',       priority: 0.6 },
    { loc: '/services',            priority: 0.9 },
    { loc: '/plans',               priority: 0.9 },
    { loc: '/terms-conditions',    priority: 0.6 },
    { loc: '/services/web-app-development', priority: 0.9 },
    { loc: '/services/architecture',        priority: 0.85 },
    { loc: '/services/ecommerce',           priority: 0.9 },
    { loc: '/services/digital-marketing',    priority: 0.85 },
    { loc: '/services/education',           priority: 0.8 },
    { loc: '/services/finance',             priority: 0.8 },
    { loc: '/services/grocery',             priority: 0.8 },
    { loc: '/services/healthcare',          priority: 0.8 },
    { loc: '/services/hospitality',         priority: 0.8 },
    { loc: '/services/ngo',                 priority: 0.8 },
    { loc: '/services/on-demand',           priority: 0.8 },
    { loc: '/services/real-estate',         priority: 0.8 },
    { loc: '/services/travel',              priority: 0.8 },
  ],
}
